2017-11-28 12:18:57 ERROR (MainThread) [homeassistant.core] Error doing job: Fatal read error on socket transport
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/selector_events.py", line 724, in _read_ready
    data = self._sock.recv(self.max_size)
TimeoutError: [Errno 60] Operation timed out
2017-11-28 13:18:12 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 182, in _step
    result = coro.throw(exc)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/homeassistant/components/discovery.py", line 127, in scan_devices
    results = yield from hass.async_add_job(_discover, netdisco)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/futures.py", line 332, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/futures.py", line 245, in result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/homeassistant/components/discovery.py", line 153, in _discover
    netdisco.scan()
  File "/Users/raul/.homeassistant/deps/lib/python/site-packages/netdisco/discovery.py", line 60, in scan
    self.gdm.scan()
  File "/Users/raul/.homeassistant/deps/lib/python/site-packages/netdisco/gdm.py", line 22, in scan
    self.update()
  File "/Users/raul/.homeassistant/deps/lib/python/site-packages/netdisco/gdm.py", line 77, in update
    sock.sendto(gdm_msg, (gdm_ip, gdm_port))
OSError: [Errno 50] Network is down
